<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta lang="en">
    <title>National Park Survey</title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="coin-slider-styles.css" type="text/css">
</head>

<body class="container">
<!--    The top left of the z pattern-->
<div class="row">
	<header>
		<h1>National Park Survey</h1>
	</header>
	<!--    The top right of the z pattern-->
	<aside>
		<nav class="">
		    <ul class="">
		        <a class="" href="index.php"><li class="button">Home</li></a>
		        <a class="" href="descriptions.php"><li class="button">Description</li></a>
		        <a class="" href="national-park.php"><li class="button">National Parks</li></a>
		        <a class="" href="survey.php"><li class="button-dif">Survey</li></a>
		    </ul>
		</nav>
	</aside>
</div>