<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
<script src="js/semantic.min.js"></script>
<script src="js/jquery-1.4.2.js"></script>
<script src="js/coin-slider.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    $('#coin-slider').coinslider({spw: 1, sph: 1, width: 960, height: 480, navigation: false, links: false, hoverPause: false });
  });
</script>